### ISSUE TITLE
Ask you to crack the Chinese mainland version of ticktick for windows

### ISSUE THREAD

**Issue by zhangweildlh** [yazdipour/cracked-ticktick-windows#2]
Hello, I ask you to crack the Chinese mainland version of ticktick for windows.

It is the same company product as ticktick, which is facing the international market and the Chinese mainland.

Official website of Chinese mainland Edition: https://dida365.com/

Download address: https://dida365.com/static/getApp/download?type=win64

**Comment by yazdipour** [comment]
I cracked this version for personal usage.
At this point,putting time to Crack the Chinese version has no income for me. So unfortunately i have to refuse.

**Comment by zhangweildlh** [comment]
Hello, I cracked it for my own use, not for commercial use. Could you please give me your guidance on what tools to use and what to modify?

**Comment by yazdipour** [comment]
i used https://github.com/dnSpy/dnSpy to find UserModel and force "pro" to TRUE and "proEndDate
 to new DateTime?(new DateTime(2030, 12, 25))
