### ISSUE TITLE
Update it for the new version?

### ISSUE THREAD

**Issue by dummifiedme** [yazdipour/cracked-ticktick-windows#3]
This is for an old version, can you work out a way for new version?

**Comment by yazdipour** [comment]
Updated 
https://github.com/yazdipour/cracked-ticktick-windows/releases/tag/3.9.0.1

**Comment by dummifiedme** [comment]
Another update pushed in. Just a reminder. 
If you have time and its possible, update :)

Thanks

**Comment by yazdipour** [comment]
https://github.com/yazdipour/cracked-ticktick-windows/releases/tag/3.9.1.0
