### ISSUE TITLE
How to crack the Chinese version of ticktick 

### ISSUE THREAD

**Issue by zhangweildlh** [yazdipour/cracked-ticktick-windows#5]
Thank you for your last guidance！
Chinese version of ticktick does obfuscated encryption；dnSpy opens the program and sees garbled code, which cannot be decompiled correctly and cannot find UserModel and force "pro" to TRUE and "proEndDate to new DateTime?(new DateTime(2030, 12, 25))。

I would like to ask for your guidance
How to properly disambiguate and decompile the Chinese version of ticktick.
I know there is no income for you to crack the Chinese version of ticktick, I am willing to express some Chinese Sichuan food and seasoning as payment.

**Comment by zhangweildlh** [comment]
https://cdn.dida365.cn/download/win64/dida_win_setup_release_x64_4071.exe

**Comment by CattoDoesCode** [comment]
@zhangweildlh can you also guide me on how to use dnSpy?

**Comment by CattoDoesCode** [comment]
can you also please guide me where specifically to force` ticktick_WPF.Models.UserModel.proEndDate=>new DateTime?(new DateTime(2030, 12, 25));` and `ticktick_WPF.pro=>true;` using dnSpy?

**Comment by zhangweildlh** [comment]
> 

At present, "dnSpy" cannot be used to crack ticktick.

**Comment by Headmower** [comment]
> > 
> 
> At present, "dnSpy" cannot be used to crack ticktick.

I've done it just today)

**Comment by zhangweildlh** [comment]
> > > 
> > 
> > 
> > At present, "dnSpy" cannot be used to crack ticktick.
> 
> I've done it just today)

Hello, can you share a copy of the new TickTick-windows crack with me?
My email address: zhangwei_ldlh@qq.com

**Comment by wsczh** [comment]
> > > 
> > 
> > 
> > At present, "dnSpy" cannot be used to crack ticktick.
> 
> I've done it just today)

Hello, can u share a copy to me! Thanks!
Email: wangsc98@foxmail.com

**Comment by Baccanoooo** [comment]
Hello, do you have the Chinese version now?
