### ISSUE TITLE
Make sure you download the 32 bit version from the website.

### ISSUE THREAD

**Issue by nikoroscalm** [yazdipour/cracked-ticktick-windows#6]
I just consider it necessary to note that the 64-bit version is downloaded from the official site by default. It's very easy to overlook this and end up its not working. Make sure you download the 32 bit version from the website.

**Comment by Gr-Nobel** [comment]
will 32 bit version work on 64 machines?

**Comment by Gr-Nobel** [comment]
Should I login then replace the file or login after replacing.
