### ISSUE TITLE
Use 4.2.6, tell me "CreateDBFailed, please make sure to run with administrator privileges"

### ISSUE THREAD

**Issue by wsczh** [yazdipour/cracked-ticktick-windows#7]
I use administrator privileges to execute it, but it still tells this.
![image](https://user-images.githubusercontent.com/47129873/190035780-32f381c9-a13a-4a54-88fc-f062fd5bcecb.png)

After close this, it has new information.

![image](https://user-images.githubusercontent.com/47129873/190035927-57313a10-918a-476e-bcaa-e87814317f14.png)

**Comment by Gr-Nobel** [comment]
download the 32 bit version to make it work.
